/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthAuthLayoutRouteImport } from './routes/_auth/_auth-layout'
import { Route as StoreLayoutRouteImport } from './routes/$store/_layout'
import { Route as StoreLayoutIndexRouteImport } from './routes/$store/_layout/index'
import { Route as AuthAuthLayoutSigninRouteImport } from './routes/_auth/_auth-layout/signin'
import { Route as StoreLayoutTagsRouteImport } from './routes/$store/_layout/tags'
import { Route as StoreLayoutProductsRouteImport } from './routes/$store/_layout/products'
import { Route as StoreLayoutOrdersRouteImport } from './routes/$store/_layout/orders'
import { Route as StoreLayoutImagesRouteImport } from './routes/$store/_layout/images'
import { Route as StoreLayoutCouponsRouteImport } from './routes/$store/_layout/coupons'
import { Route as StoreLayoutCategoriesRouteImport } from './routes/$store/_layout/categories'
import { Route as StoreLayoutSettingsShippingRouteImport } from './routes/$store/_layout/settings_.shipping'
import { Route as StoreLayoutSettingsPaymentRouteImport } from './routes/$store/_layout/settings_.payment'
import { Route as StoreLayoutSettingsGeneralRouteImport } from './routes/$store/_layout/settings_.general'
import { Route as StoreLayoutProductsAddRouteImport } from './routes/$store/_layout/products_.add'
import { Route as StoreLayoutAdminPaymentMethodsRouteImport } from './routes/$store/_layout/admin_.payment-methods'

const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/_auth/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLayoutRoute = StoreLayoutRouteImport.update({
  id: '/$store/_layout',
  path: '/$store',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLayoutIndexRoute = StoreLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreLayoutRoute,
} as any)
const AuthAuthLayoutSigninRoute = AuthAuthLayoutSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const StoreLayoutTagsRoute = StoreLayoutTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => StoreLayoutRoute,
} as any)
const StoreLayoutProductsRoute = StoreLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StoreLayoutRoute,
} as any)
const StoreLayoutOrdersRoute = StoreLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoreLayoutRoute,
} as any)
const StoreLayoutImagesRoute = StoreLayoutImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => StoreLayoutRoute,
} as any)
const StoreLayoutCouponsRoute = StoreLayoutCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => StoreLayoutRoute,
} as any)
const StoreLayoutCategoriesRoute = StoreLayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StoreLayoutRoute,
} as any)
const StoreLayoutSettingsShippingRoute =
  StoreLayoutSettingsShippingRouteImport.update({
    id: '/settings_/shipping',
    path: '/settings/shipping',
    getParentRoute: () => StoreLayoutRoute,
  } as any)
const StoreLayoutSettingsPaymentRoute =
  StoreLayoutSettingsPaymentRouteImport.update({
    id: '/settings_/payment',
    path: '/settings/payment',
    getParentRoute: () => StoreLayoutRoute,
  } as any)
const StoreLayoutSettingsGeneralRoute =
  StoreLayoutSettingsGeneralRouteImport.update({
    id: '/settings_/general',
    path: '/settings/general',
    getParentRoute: () => StoreLayoutRoute,
  } as any)
const StoreLayoutProductsAddRoute = StoreLayoutProductsAddRouteImport.update({
  id: '/products_/add',
  path: '/products/add',
  getParentRoute: () => StoreLayoutRoute,
} as any)
const StoreLayoutAdminPaymentMethodsRoute =
  StoreLayoutAdminPaymentMethodsRouteImport.update({
    id: '/admin_/payment-methods',
    path: '/admin/payment-methods',
    getParentRoute: () => StoreLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$store': typeof StoreLayoutRouteWithChildren
  '/': typeof AuthAuthLayoutRouteWithChildren
  '/$store/categories': typeof StoreLayoutCategoriesRoute
  '/$store/coupons': typeof StoreLayoutCouponsRoute
  '/$store/images': typeof StoreLayoutImagesRoute
  '/$store/orders': typeof StoreLayoutOrdersRoute
  '/$store/products': typeof StoreLayoutProductsRoute
  '/$store/tags': typeof StoreLayoutTagsRoute
  '/signin': typeof AuthAuthLayoutSigninRoute
  '/$store/': typeof StoreLayoutIndexRoute
  '/$store/admin/payment-methods': typeof StoreLayoutAdminPaymentMethodsRoute
  '/$store/products/add': typeof StoreLayoutProductsAddRoute
  '/$store/settings/general': typeof StoreLayoutSettingsGeneralRoute
  '/$store/settings/payment': typeof StoreLayoutSettingsPaymentRoute
  '/$store/settings/shipping': typeof StoreLayoutSettingsShippingRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthAuthLayoutRouteWithChildren
  '/$store/categories': typeof StoreLayoutCategoriesRoute
  '/$store/coupons': typeof StoreLayoutCouponsRoute
  '/$store/images': typeof StoreLayoutImagesRoute
  '/$store/orders': typeof StoreLayoutOrdersRoute
  '/$store/products': typeof StoreLayoutProductsRoute
  '/$store/tags': typeof StoreLayoutTagsRoute
  '/signin': typeof AuthAuthLayoutSigninRoute
  '/$store': typeof StoreLayoutIndexRoute
  '/$store/admin/payment-methods': typeof StoreLayoutAdminPaymentMethodsRoute
  '/$store/products/add': typeof StoreLayoutProductsAddRoute
  '/$store/settings/general': typeof StoreLayoutSettingsGeneralRoute
  '/$store/settings/payment': typeof StoreLayoutSettingsPaymentRoute
  '/$store/settings/shipping': typeof StoreLayoutSettingsShippingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$store/_layout': typeof StoreLayoutRouteWithChildren
  '/_auth/_auth-layout': typeof AuthAuthLayoutRouteWithChildren
  '/$store/_layout/categories': typeof StoreLayoutCategoriesRoute
  '/$store/_layout/coupons': typeof StoreLayoutCouponsRoute
  '/$store/_layout/images': typeof StoreLayoutImagesRoute
  '/$store/_layout/orders': typeof StoreLayoutOrdersRoute
  '/$store/_layout/products': typeof StoreLayoutProductsRoute
  '/$store/_layout/tags': typeof StoreLayoutTagsRoute
  '/_auth/_auth-layout/signin': typeof AuthAuthLayoutSigninRoute
  '/$store/_layout/': typeof StoreLayoutIndexRoute
  '/$store/_layout/admin_/payment-methods': typeof StoreLayoutAdminPaymentMethodsRoute
  '/$store/_layout/products_/add': typeof StoreLayoutProductsAddRoute
  '/$store/_layout/settings_/general': typeof StoreLayoutSettingsGeneralRoute
  '/$store/_layout/settings_/payment': typeof StoreLayoutSettingsPaymentRoute
  '/$store/_layout/settings_/shipping': typeof StoreLayoutSettingsShippingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$store'
    | '/'
    | '/$store/categories'
    | '/$store/coupons'
    | '/$store/images'
    | '/$store/orders'
    | '/$store/products'
    | '/$store/tags'
    | '/signin'
    | '/$store/'
    | '/$store/admin/payment-methods'
    | '/$store/products/add'
    | '/$store/settings/general'
    | '/$store/settings/payment'
    | '/$store/settings/shipping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$store/categories'
    | '/$store/coupons'
    | '/$store/images'
    | '/$store/orders'
    | '/$store/products'
    | '/$store/tags'
    | '/signin'
    | '/$store'
    | '/$store/admin/payment-methods'
    | '/$store/products/add'
    | '/$store/settings/general'
    | '/$store/settings/payment'
    | '/$store/settings/shipping'
  id:
    | '__root__'
    | '/$store/_layout'
    | '/_auth/_auth-layout'
    | '/$store/_layout/categories'
    | '/$store/_layout/coupons'
    | '/$store/_layout/images'
    | '/$store/_layout/orders'
    | '/$store/_layout/products'
    | '/$store/_layout/tags'
    | '/_auth/_auth-layout/signin'
    | '/$store/_layout/'
    | '/$store/_layout/admin_/payment-methods'
    | '/$store/_layout/products_/add'
    | '/$store/_layout/settings_/general'
    | '/$store/_layout/settings_/payment'
    | '/$store/_layout/settings_/shipping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreLayoutRoute: typeof StoreLayoutRouteWithChildren
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/_auth-layout': {
      id: '/_auth/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$store/_layout': {
      id: '/$store/_layout'
      path: '/$store'
      fullPath: '/$store'
      preLoaderRoute: typeof StoreLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$store/_layout/': {
      id: '/$store/_layout/'
      path: '/'
      fullPath: '/$store/'
      preLoaderRoute: typeof StoreLayoutIndexRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/_auth/_auth-layout/signin': {
      id: '/_auth/_auth-layout/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthAuthLayoutSigninRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/$store/_layout/tags': {
      id: '/$store/_layout/tags'
      path: '/tags'
      fullPath: '/$store/tags'
      preLoaderRoute: typeof StoreLayoutTagsRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/products': {
      id: '/$store/_layout/products'
      path: '/products'
      fullPath: '/$store/products'
      preLoaderRoute: typeof StoreLayoutProductsRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/orders': {
      id: '/$store/_layout/orders'
      path: '/orders'
      fullPath: '/$store/orders'
      preLoaderRoute: typeof StoreLayoutOrdersRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/images': {
      id: '/$store/_layout/images'
      path: '/images'
      fullPath: '/$store/images'
      preLoaderRoute: typeof StoreLayoutImagesRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/coupons': {
      id: '/$store/_layout/coupons'
      path: '/coupons'
      fullPath: '/$store/coupons'
      preLoaderRoute: typeof StoreLayoutCouponsRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/categories': {
      id: '/$store/_layout/categories'
      path: '/categories'
      fullPath: '/$store/categories'
      preLoaderRoute: typeof StoreLayoutCategoriesRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/settings_/shipping': {
      id: '/$store/_layout/settings_/shipping'
      path: '/settings/shipping'
      fullPath: '/$store/settings/shipping'
      preLoaderRoute: typeof StoreLayoutSettingsShippingRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/settings_/payment': {
      id: '/$store/_layout/settings_/payment'
      path: '/settings/payment'
      fullPath: '/$store/settings/payment'
      preLoaderRoute: typeof StoreLayoutSettingsPaymentRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/settings_/general': {
      id: '/$store/_layout/settings_/general'
      path: '/settings/general'
      fullPath: '/$store/settings/general'
      preLoaderRoute: typeof StoreLayoutSettingsGeneralRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/products_/add': {
      id: '/$store/_layout/products_/add'
      path: '/products/add'
      fullPath: '/$store/products/add'
      preLoaderRoute: typeof StoreLayoutProductsAddRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
    '/$store/_layout/admin_/payment-methods': {
      id: '/$store/_layout/admin_/payment-methods'
      path: '/admin/payment-methods'
      fullPath: '/$store/admin/payment-methods'
      preLoaderRoute: typeof StoreLayoutAdminPaymentMethodsRouteImport
      parentRoute: typeof StoreLayoutRoute
    }
  }
}

interface StoreLayoutRouteChildren {
  StoreLayoutCategoriesRoute: typeof StoreLayoutCategoriesRoute
  StoreLayoutCouponsRoute: typeof StoreLayoutCouponsRoute
  StoreLayoutImagesRoute: typeof StoreLayoutImagesRoute
  StoreLayoutOrdersRoute: typeof StoreLayoutOrdersRoute
  StoreLayoutProductsRoute: typeof StoreLayoutProductsRoute
  StoreLayoutTagsRoute: typeof StoreLayoutTagsRoute
  StoreLayoutIndexRoute: typeof StoreLayoutIndexRoute
  StoreLayoutAdminPaymentMethodsRoute: typeof StoreLayoutAdminPaymentMethodsRoute
  StoreLayoutProductsAddRoute: typeof StoreLayoutProductsAddRoute
  StoreLayoutSettingsGeneralRoute: typeof StoreLayoutSettingsGeneralRoute
  StoreLayoutSettingsPaymentRoute: typeof StoreLayoutSettingsPaymentRoute
  StoreLayoutSettingsShippingRoute: typeof StoreLayoutSettingsShippingRoute
}

const StoreLayoutRouteChildren: StoreLayoutRouteChildren = {
  StoreLayoutCategoriesRoute: StoreLayoutCategoriesRoute,
  StoreLayoutCouponsRoute: StoreLayoutCouponsRoute,
  StoreLayoutImagesRoute: StoreLayoutImagesRoute,
  StoreLayoutOrdersRoute: StoreLayoutOrdersRoute,
  StoreLayoutProductsRoute: StoreLayoutProductsRoute,
  StoreLayoutTagsRoute: StoreLayoutTagsRoute,
  StoreLayoutIndexRoute: StoreLayoutIndexRoute,
  StoreLayoutAdminPaymentMethodsRoute: StoreLayoutAdminPaymentMethodsRoute,
  StoreLayoutProductsAddRoute: StoreLayoutProductsAddRoute,
  StoreLayoutSettingsGeneralRoute: StoreLayoutSettingsGeneralRoute,
  StoreLayoutSettingsPaymentRoute: StoreLayoutSettingsPaymentRoute,
  StoreLayoutSettingsShippingRoute: StoreLayoutSettingsShippingRoute,
}

const StoreLayoutRouteWithChildren = StoreLayoutRoute._addFileChildren(
  StoreLayoutRouteChildren,
)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutSigninRoute: typeof AuthAuthLayoutSigninRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutSigninRoute: AuthAuthLayoutSigninRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StoreLayoutRoute: StoreLayoutRouteWithChildren,
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
